plugins:
  - jekyll-remote-theme
remote_theme: benbalter/retlab
title: Groundhog
description: A utility for testing webcaches
logo: https://image.shutterstock.com/image-vector/cute-cartoon-marmot-looking-hole-600w-584357575.jpg
